spring:
  application:
    name: pay-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    sentinel:
      enabled: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://100.86.250.112:13306/test_pay?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

rocketmq:
  topic:
    pay_success_normal: pay-success-normal
    pay_success_group_buy: pay-success-group-buy
    pay_success_seckill: pay-success-seckill
    order_close_normal: order-close-normal
    order_close_group_buy: order-close-group-buy
    order_close_seckill: order-close-seckill
    pay_refund_normal: pay-refund-normal
    pay_refund_group_buy: pay-refund-group-buy
    pay_refund_seckill: pay-refund-seckill
    pay_refund_normal_result: pay-refund-normal-result
    pay_refund_group_buy_result: pay-refund-group-buy-result
    pay_refund_seckill_result: pay-refund-seckill-result

app:
  config:
    api-version: v1
    cross-origin: '*'
    group-buy-market:
      api-url: http://127.0.0.1:8093
      source: s01
      chanel: c01
    no-market:
      api-url: http://127.0.0.1:8093
      source: s01
      chanel: c01

weixin:
  config:
    originalid: test-original
    token: test-token
    app-id: test-app-id
    app-secret: test-app-secret
    template_id: test-template

alipay:
  enabled: true
  app_id: test-app
  merchant_private_key: test-private
  alipay_public_key: test-public
  notify_url: http://127.0.0.1/mock-notify
  return_url: http://127.0.0.1/mock-return
  gatewayUrl: http://127.0.0.1/mock-gateway
  mock-refund: true

logging:
  level:
    root: info
