rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:100.86.250.112:9876}
  producer:
    group: seckill-service-producer

app:
  rocketmq:
    topic:
      seckillOrderCreate: seckill-order-create
      orderPaidSeckill: order-paid-seckill
      orderCloseSeckillMarket: order-close-seckill-market
      seckillStockDeduct: seckill-stock-deduct
      orderRefundSeckill: order-refund-seckill
    consumerGroup:
      seckillOrderCreate: CG_SECKILL_ORDER_CREATE
      orderPaidSeckill: CG_ORDER_PAID_SECKILL
      orderCloseSeckill: CG_ORDER_CLOSE_SECKILL_MARKET
      seckillStockDeduct: CG_SECKILL_STOCK_DEDUCT
      payRefundSeckill: CG_SECKILL_PAY_REFUND
