rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:100.86.250.112:9876}
  producer:
    group: order-service-producer
    send-message-timeout: 3000

app:
  order:
    allow-direct-normal-create-order: true
    get-pay-url-pending-retries: 6
    get-pay-url-pending-wait-ms: 50
    internal-create-token: ""
  rocketmq:
    topic:
      paySuccessNormal: pay-success-normal
      paySuccessGroupBuy: pay-success-group-buy
      paySuccessSeckill: pay-success-seckill
      orderCloseNormal: order-close-normal
      orderCloseGroupBuy: order-close-group-buy
      orderCloseSeckill: order-close-seckill
      payRefundNormal: pay-refund-normal
      payRefundGroupBuy: pay-refund-group-buy
      payRefundSeckill: pay-refund-seckill
      payRefundNormalResult: pay-refund-normal-result
      payRefundGroupBuyResult: pay-refund-group-buy-result
      payRefundSeckillResult: pay-refund-seckill-result
      groupBuySuccessNotify: group-buy-success-notify
      orderPaidNormal: order-paid-normal
      orderPaidGroupBuy: order-paid-group_buy
      orderPaidSeckill: order-paid-seckill
      orderShipTask: order-ship-task
      seckillOrderCreate: seckill-order-create
      normalOrderCreate: normal-order-create
      groupBuyOrderCreate: group-buy-order-create
    consumerGroup:
      paySuccessNormal: CG_PAY_SUCCESS_NORMAL
      paySuccessGroupBuy: CG_PAY_SUCCESS_GROUP_BUY
      paySuccessSeckill: CG_PAY_SUCCESS_SECKILL
      orderCloseNormal: CG_ORDER_CLOSE_NORMAL
      orderCloseGroupBuy: CG_ORDER_CLOSE_GROUP_BUY
      orderCloseSeckill: CG_ORDER_CLOSE_SECKILL
      payRefundNormal: CG_PAY_REFUND_NORMAL
      payRefundGroupBuy: CG_PAY_REFUND_GROUP_BUY
      payRefundSeckill: CG_PAY_REFUND_SECKILL
      payRefundNormalResult: CG_PAY_REFUND_NORMAL_RESULT
      payRefundGroupBuyResult: CG_PAY_REFUND_GROUP_BUY_RESULT
      payRefundSeckillResult: CG_PAY_REFUND_SECKILL_RESULT
      groupBuySuccessNotify: CG_GROUP_BUY_SUCCESS_NOTIFY
      orderShipTask: CG_ORDER_SHIP_TASK
      seckillOrderCreate: CG_SECKILL_ORDER_CREATE_ORDER
      normalOrderCreate: CG_NORMAL_ORDER_CREATE
      groupBuyOrderCreate: CG_GROUP_BUY_ORDER_CREATE
