

spring:
  application:
    name: Permission-System
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.79.165:13306/pern
    username: root
    password: 123456
  jpa:
    open-in-view: false
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #开启驼峰命名映射的开关
      map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  helper-dialect: mysql

openai:
  api:
    key=your-openai-api-key:

documents:
  path=documents:

server:
  port: 8084
  servlet:
    session:
      timeout: 10000000000000000
    # 设置响应的字符编码，避免流式返回输出乱码
    encoding:
      charset: utf-8
      force: true
      enabled: true


