FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY locust /app/locust

ENV PORT=7000
ENV NOTIFY_URL=http://pay:8095/api/v1/alipay/alipay_notify_url
ENV PUBLIC_BASE_URL=http://100.86.250.112:7000

CMD ["python", "locust/seckill/mock_alipay.py"]
