rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:100.86.250.112:9876}
  producer:
    group: group-buy-service-producer

app:
  rocketmq:
    topic:
      orderPaidGroupBuy: order-paid-group_buy
      groupBuySuccessNotify: group-buy-success-notify
      groupBuyTimeoutRefund: group-buy-timeout-refund
      orderCloseGroupBuyMarket: order-close-group-buy-market
      orderRefundGroupBuy: order-refund-group-buy
    consumerGroup:
      orderPaidGroupBuy: CG_GROUP_BUY_ORDER_PAID
      groupBuyTimeoutRefund: CG_GROUP_BUY_TIMEOUT_REFUND
      payRefundGroupBuy: CG_GROUP_BUY_PAY_REFUND
      orderCloseGroupBuy: CG_GROUP_BUY_ORDER_CLOSE
