server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/group_buy_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        ip: 100.67.209.67
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: group-buy-service-producer

# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

app:
  rocketmq:
    topic:
      orderPaidGroupBuy: order-paid-group_buy
      groupBuySuccessNotify: group-buy-success-notify
    consumerGroup:
      orderPaidGroupBuy: CG_GROUP_BUY_ORDER_PAID

logging:
  level:
    com.yue.groupbuy: info


# 日志上报 ELK
logstash:
  host: 127.0.0.1
