spring:
  application:
    name: group-buy-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    sentinel:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://100.86.250.112:13306/test_group_buy_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  data:
    redis:
      host: 100.86.250.112
      port: 16379
      database: 0
      timeout: 3000ms
      client-name: groupbuy-redisson
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://100.86.250.112:16379"
          database: 0
          clientName: groupbuy-redisson
          connectionPoolSize: 10
          connectionMinimumIdleSize: 5
          idleConnectionTimeout: 30000
          pingConnectionInterval: 60000
          retryAttempts: 3
          retryInterval: 1000
          connectTimeout: 5000
          timeout: 3000
          keepAlive: true

rocketmq:
  producer:
    group: group-buy-service-producer

app:
  rocketmq:
    topic:
      orderPaidGroupBuy: order-paid-group_buy
      groupBuySuccessNotify: group-buy-success-notify
      groupBuyTimeoutRefund: group-buy-timeout-refund
      orderCloseGroupBuyMarket: order-close-group-buy-market
      orderRefundGroupBuy: order-refund-group-buy
    consumerGroup:
      orderPaidGroupBuy: CG_GROUP_BUY_ORDER_PAID
      groupBuyTimeoutRefund: CG_GROUP_BUY_TIMEOUT_REFUND
      payRefundGroupBuy: CG_GROUP_BUY_PAY_REFUND
      orderCloseGroupBuy: CG_GROUP_BUY_ORDER_CLOSE

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

logging:
  level:
    com.yue.groupbuy: info
